
(dockerfile-mode . [(20200106 2126) ((emacs (24)) (s (1 12))) "Major mode for editing Docker's Dockerfiles" single ((:commit . "d31f7685ebc5832d957e25070a930aa42984327d") (:url . "https://github.com/spotify/dockerfile-mode"))])
